"eupr": '1', 
"creos": '1', 
"var": '1', 
"mag": '1', 
"bron": '1', 
"cyc": '1', 
"r secl": '1', 
"abar": '1', 
"eyphr": '1', 
"sill": '1', 
"v rt": '1', 
"nat": '1', 
"asa f": '1', 
"v odor": '1', 
"m art": '1', 
"mur ac": '1', 
"scil": '1', 
"mezar": '1', 
"stont": '1', 
"mac": '1', 
"conth": '1', 
"mago": '1', 
"phosphqac": '1', 
"ammon": '1', 
"bav": '1'
// "a crud": 'ant-c', 
// "a cr": 'ant-c',
// "a tart": 'ant-t',
// "a mur": 'am-m',