const remediesNotInDB = [
{ shortName: "abies-c", name: "abies canadensis" }, 
{ shortName: "abies-n", name: "abies nigra" }, 
{ shortName: "acal", name: "acalypha indica" }, 
{ shortName: "absin", name: "absinthium" }, 
{ shortName: "acet-ac", name: "acetic acid" }, 
{ shortName: "acon-c", name: "aconitum cammarum" }, 
{ shortName: "acon-f", name: "aconitum ferox" }, 
{ shortName: "acon-l", name: "aconitum lycotonum" }, 
{ shortName: "act-sp", name: "actaea spicata" }, 
{ shortName: "aesc-g", name: "aesculus glabra" }, 
{ shortName: "agar-em", name: "agaricus emeticus" }, 
{ shortName: "agar-ph", name: "agaricus phalloides" }, 
{ shortName: "alco", name: "alcohol" }, 
{ shortName: "ail", name: "ailanthus" }, 
{ shortName: "all-s", name: "allium sativum" }, 
{ shortName: "alst", name: "alstonia constricta" }, 
{ shortName: "alum-m", name: "aluminium metallicum" }, 
{ shortName: "aloe", name: "aloe socotrina" }, 
{ shortName: "am-be", name: "ammonium benzoicum" }, 
{ shortName: "am-br", name: "ammonium bromatum" }, 
{ shortName: "am-caust", name: "ammonium causticum" }, 
{ shortName: "aml-n", name: "amyl nitrite" }, 
{ shortName: "ambro", name: "ambrosia artemisiae folia" }, 
{ shortName: "ammc", name: "ammoniacum gummi" }, 
{ shortName: "amph", name: "amphisboena" }, 
{ shortName: "anac-oc", name: "anacardium occidentale" }, 
{ shortName: "amyg", name: "amygdalae amarae aqua" }, 
{ shortName: "anag", name: "anagallis aryensis" }, 
{ shortName: "anan", name: "anantherum muricatum" }, 
{ shortName: "ang", name: "angustura vera" }, 
{ shortName: "anil", name: "anilinum" }, 
{ shortName: "anis", name: "anisum stellatum" }, 
{ shortName: "ant-a", name: "antimonium arsenicosum" }, 
{ shortName: "ant-chl", name: "antimonium chloridum" }, 
{ shortName: "ant-ox", name: "antimonium oxydatum" }, 
{ shortName: "ant-s", name: "antimonium sulph auratum" }, 
{ shortName: "anthro", name: "anthrokokali" }, 
{ shortName: "anthr", name: "anthracinum" }, 
{ shortName: "ap-g", name: "apium graveolens" }, 
{ shortName: "aphis", name: "aphis chenopodii glauci" }, 
{ shortName: "anth", name: "anthemis nobilis" }, 
{ shortName: "apoc-a", name: "apocynum androsaemifolium" }, 
{ shortName: "apom", name: "apomorphium" }, 
{ shortName: "aral", name: "aralia racemosa" }, 
{ shortName: "aran-s", name: "aranea scinencia" }, 
{ shortName: "arg-c", name: "argentum cyanidum" }, 
{ shortName: "aran", name: "aranea diadema" }, 
{ shortName: "arg-mur", name: "argentum muriaticum" }, 
{ shortName: "ars-h", name: "arsenicum hydrogenisatum" }, 
{ shortName: "ars-n", name: "arsenicum nitricum" }, 
{ shortName: "ars-m", name: "arsenicum metallicum" }, 
{ shortName: "ars-s-f", name: "arsenicum sulphuratum flavun" }, 
{ shortName: "ars-s-r", name: "arsenicum sulphuratum rubrun" }, 
{ shortName: "art-v", name: "artemisia vulgaris" }, 
{ shortName: "arum-d", name: "arum dracontium" }, 
{ shortName: "arum-m", name: "arum maculatum" }, 
{ shortName: "arum-i", name: "arum italicum" }, 
{ shortName: "arund", name: "arundo mauritanica" }, 
{ shortName: "arund-d", name: "arundo donax" }, 
{ shortName: "asc-c", name: "asclepias cornuti (syriaca)" }, 
{ shortName: "asar", name: "asarum europaeum" }, 
{ shortName: "asc-t", name: "asclepias tuberosa" }, 
{ shortName: "asim", name: "asimina triloba" }, 
{ shortName: "aspar", name: "asparagus officinalis" }, 
{ shortName: "aster", name: "asterias rubens" }, 
{ shortName: "astac", name: "astacus fluviatilis" }, 
{ shortName: "atro", name: "atropinium" }, 
{ shortName: "atro-s", name: "atropia sulphurica" }, 
{ shortName: "aur-m-n", name: "aurum muriaticum natronatum" }, 
{ shortName: "aur-s", name: "aurum sulphuratum" }, 
{ shortName: "bad", name: "badiaga" }, 
{ shortName: "bals", name: "balsamum peruvianum" }, 
{ shortName: "bapt", name: "baptisia tinctoria" }, 
{ shortName: "bar-i", name: "baryta iodata" }, 
{ shortName: "bar-ac", name: "baryta acetica" }, 
{ shortName: "bart", name: "bartfelder (acid spring)" }, 
{ shortName: "bell-p", name: "bellis perennis" }, 
{ shortName: "benz", name: "benzinum" }, 
{ shortName: "benz-n", name: "benzinum nitricum" }, 
{ shortName: "blat", name: "blatta americana" }, 
{ shortName: "bism-ox", name: "bismuthum oxidum" }, 
{ shortName: "bol", name: "boletus laricis" }, 
{ shortName: "blatta", name: "blatta orientalis" }, 
{ shortName: "bor-ac", name: "boracicum acidum" }, 
{ shortName: "berb", name: "berberis vulgaris" }, 
{ shortName: "bov", name: "bovista" }, 
{ shortName: "both", name: "bothrops lanceolatus" }, 
{ shortName: "brach", name: "brachyglottis repens" }, 
{ shortName: "benz-ac", name: "benzoic acid" }, 
{ shortName: "bry", name: "bryonia alba" }, 
{ shortName: "bufo-s", name: "bufo sahytiensis" }, 
{ shortName: "bruc", name: "brucea antidysenterica" }, 
{ shortName: "bufo", name: "bufo rana" }, 
{ shortName: "cadm", name: "cadmium sulphuratum" }, 
{ shortName: "cahin", name: "cahinca" }, 
{ shortName: "calad", name: "caladium seguinum" }, 
{ shortName: "cain", name: "cainca" }, 
{ shortName: "calc-ar", name: "calcarea arsenica" }, 
{ shortName: "calc-caust", name: "calcarea caustica" }, 
{ shortName: "caj", name: "cajuputum" }, 
{ shortName: "calc-f", name: "calcarea fluorata" }, 
{ shortName: "calc-ac", name: "calcarea acetica" }, 
{ shortName: "calen", name: "calendula officinalis" }, 
{ shortName: "calo", name: "calotropis gigantea" }, 
{ shortName: "calli", name: "calliandra houstoni" }, 
{ shortName: "camph", name: "camphora officinarum" }, 
{ shortName: "canch", name: "canchalagua" }, 
{ shortName: "calt", name: "caltha palustris" }, 
{ shortName: "carb-ac", name: "carbolic acid" }, 
{ shortName: "carb-h", name: "carboneum hydrogenisatum" }, 
{ shortName: "carb-o", name: "carboneum oxygenisatum" }, 
{ shortName: "card-b", name: "carduus benedictus" }, 
{ shortName: "carl", name: "carlsbad" }, 
{ shortName: "casc", name: "cascarilla" }, 
{ shortName: "cast-eq", name: "castor equi" }, 
{ shortName: "cast-v", name: "castanea vesca" }, 
{ shortName: "cast", name: "castoreum" }, 
{ shortName: "caul", name: "caulophyllum thalictroides" }, 
{ shortName: "cean", name: "ceanothus americanus" }, 
{ shortName: "cedr", name: "cedron" }, 
{ shortName: "cer-s", name: "cereus serpentaria" }, 
{ shortName: "cent", name: "centaurea tagana" }, 
{ shortName: "cet", name: "cetrararia islandica" }, 
{ shortName: "cere-b", name: "cereus bonplandii" }, 
{ shortName: "chel", name: "chelidonium majus" }, 
{ shortName: "chen-an", name: "chenopodium anthelminticum" }, 
{ shortName: "chen-v", name: "chenopodium vulvaria" }, 
{ shortName: "chim", name: "chimaphila umbellata" }, 
{ shortName: "chen", name: "chenopodium glauci aphis" }, 
{ shortName: "chim-m", name: "chimaphila maculata" }, 
{ shortName: "chin-b", name: "chininum brom" }, 
{ shortName: "chin-s", name: "chininum sulphuricum" }, 
{ shortName: "chin", name: "china officinalis" }, 
{ shortName: "chion", name: "chionanthus virginica" }, 
{ shortName: "chlf", name: "chloroformium" }, 
{ shortName: "chlol", name: "chloralum" }, 
{ shortName: "chlor", name: "chlorum" }, 
{ shortName: "chol", name: "cholesterinum" }, 
{ shortName: "chr-ac", name: "chromicum acidum" }, 
{ shortName: "chr-ox", name: "chromicum oxydatum" }, 
{ shortName: "cimic", name: "cimicifuga racemosa" }, 
{ shortName: "cimx", name: "cimex" }, 
{ shortName: "cinch-b", name: "cinchona boliviana" }, 
{ shortName: "cinch", name: "cinchonium sulphuricum" }, 
{ shortName: "cinnb", name: "cinnabaris" }, 
{ shortName: "cinnam", name: "cinnamomum" }, 
{ shortName: "cit-1", name: "citrus limonum" }, 
{ shortName: "cit-ac", name: "citricum acidum" }, 
{ shortName: "cit-v", name: "citrus vulgaris" }, 
{ shortName: "cob", name: "cobaltum" }, 
{ shortName: "cocain-m", name: "cocainum muriaticum" }, 
{ shortName: "coca", name: "coca" }, 
{ shortName: "cocc-s", name: "coccinella septempunctata" }, 
{ shortName: "coch", name: "cochlearia armoracia" }, 
{ shortName: "cod", name: "codeinum" }, 
{ shortName: "coff", name: "coffea cruda" }, 
{ shortName: "colch", name: "colchicum autumnale" }, 
{ shortName: "coff-t", name: "coffea tosta" }, 
{ shortName: "coll", name: "collinsonia canadensis" }, 
{ shortName: "colos", name: "colostrum" }, 
{ shortName: "com", name: "comocladia dentata" }, 
{ shortName: "cond", name: "cundurango" }, 
{ shortName: "conv", name: "convallaria majalis" }, 
{ shortName: "conv-d", name: "convolvulus duartinus" }, 
{ shortName: "cop", name: "copaiva officinalis" }, 
{ shortName: "cor-r", name: "corallium rubrum" }, 
{ shortName: "cori-r", name: "coriaria ruscifolia" }, 
{ shortName: "corn-f", name: "cornus florida" }, 
{ shortName: "corn-s", name: "cornus seriea" }, 
{ shortName: "corn", name: "cornus circinata" }, 
{ shortName: "cot", name: "cotyledon umbilicus" }, 
{ shortName: "crot-c", name: "crotalus cascavella" }, 
{ shortName: "croc", name: "crocus sativus" }, 
{ shortName: "cupr-ac", name: "cuprum aceticum" }, 
{ shortName: "culx", name: "culex moscae" }, 
{ shortName: "cub", name: "cubeba officinalis" }, 
{ shortName: "cupr-ar", name: "cuprum arsenicosum" }, 
{ shortName: "cupr-s", name: "cuprum sulphuricum" }, 
{ shortName: "cupr-n", name: "cuprum nitricum" }, 
{ shortName: "cur", name: "curare" }, 
{ shortName: "cypr", name: "cypripedium pubescens" }, 
{ shortName: "cycl", name: "cyclamen europaeum" }, 
{ shortName: "daph", name: "daphne indica" }, 
{ shortName: "der", name: "derris pinnata" }, 
{ shortName: "dig", name: "digitalis purpurea" }, 
{ shortName: "dios", name: "dioscorea villosa" }, 
{ shortName: "dirc", name: "dirca palustris" }, 
{ shortName: "dol", name: "dolichos pruriens" }, 
{ shortName: "dor", name: "doryphora" }, 
{ shortName: "dub", name: "duboisinum" }, 
{ shortName: "echi", name: "echinacea angustifolia" }, 
{ shortName: "elaps", name: "elaps corallinus" }, 
{ shortName: "blat", name: "elaterium" }, 
{ shortName: "epig", name: "epigea repens" }, 
{ shortName: "erech", name: "erechthites hieracifolia" }, 
{ shortName: "equis", name: "equisetum hyemale" }, 
{ shortName: "erig", name: "erigeron canadense" }, 
{ shortName: "ery-a", name: "eryngium aquaticum" }, 
{ shortName: "eucal", name: "eucalyptus globulus" }, 
{ shortName: "eug", name: "eugenia jambos" }, 
{ shortName: "euon", name: "euonymus europaeus" }, 
{ shortName: "ether", name: "ether" }, 
{ shortName: "eup-pur", name: "eupatorium purpureum" }, 
{ shortName: "eupho", name: "euphorbium" }, 
{ shortName: "euphr", name: "euphrasia officinalis" }, 
{ shortName: "ferr-ac", name: "ferrum aceticum" }, 
{ shortName: "fago", name: "fagopyrum" }, 
{ shortName: "ferr-ar", name: "ferrum arsenicosum" }, 
{ shortName: "eupi", name: "fupion" }, 
{ shortName: "ferr-ma", name: "ferrum magneticum" }, 
{ shortName: "ferr-m", name: "ferrum muriaticum" }, 
{ shortName: "ferr-pic", name: "ferrum picricum" }, 
{ shortName: "ferr-s", name: "ferrum sulphuricum" }, 
{ shortName: "fil", name: "filix mas" }, 
{ shortName: "form", name: "formica rufa" }, 
{ shortName: "frag-v", name: "fragaria vesca" }, 
{ shortName: "gad", name: "gadus morrhua" }, 
{ shortName: "gall-ac", name: "gallicum acidum" }, 
{ shortName: "gels", name: "gelsemium sempervirens" }, 
{ shortName: "gamb", name: "gambogia" }, 
{ shortName: "gent-c", name: "gentiana cruciata" }, 
{ shortName: "genist", name: "genista tinctoria" }, 
{ shortName: "ger", name: "geranium maculatum" }, 
{ shortName: "get", name: "gettisburg water" }, 
{ shortName: "gent-l", name: "gentiana lutea" }, 
{ shortName: "gland", name: "glanderine" }, 
{ shortName: "glon", name: "glonoin" }, 
{ shortName: "gins", name: "ginseng" }, 
{ shortName: "goss", name: "gossypium herbaceum" }, 
{ shortName: "gnaph", name: "gnaphalium" }, 
{ shortName: "gran", name: "granatum punica" }, 
{ shortName: "grin", name: "grindelia robusta" }, 
{ shortName: "grat", name: "gratiola officinalis" }, 
{ shortName: "gua", name: "guaco" }, 
{ shortName: "guano", name: "guano australis" }, 
{ shortName: "guar", name: "guarana" }, 
{ shortName: "gymn", name: "gymnocladus" }, 
{ shortName: "haem", name: "haematoxylon" }, 
{ shortName: "guare", name: "guarea" }, 
{ shortName: "hedeo", name: "hedeoma pulegioides" }, 
{ shortName: "hecla", name: "hecla lava" }, 
{ shortName: "helod", name: "heloderma" }, 
{ shortName: "hep", name: "hepar sulphuris calcareum" }, 
{ shortName: "helon", name: "helonias dioica" }, 
{ shortName: "hippoz", name: "hippozanium" }, 
{ shortName: "hipp", name: "hippomanes" }, 
{ shortName: "hura", name: "hura braziliensis" }, 
{ shortName: "hom", name: "homarus" }, 
{ shortName: "hydr-ac", name: "hydrocyanicum acidum" }, 
{ shortName: "hydrang", name: "hydrangea arborescens" }, 
{ shortName: "hyper", name: "hypericum perforatum" }, 
{ shortName: "hyos", name: "hyoscyamus niger" }, 
{ shortName: "iber", name: "iberis amara" }, 
{ shortName: "ictod", name: "ictodes foetida" }, 
{ shortName: "hydrc", name: "hydrocotyle asiatica" }, 
{ shortName: "ill", name: "illicium anisatum" }, 
{ shortName: "ind", name: "indium metallicum" }, 
{ shortName: "indg", name: "indigo" }, 
{ shortName: "inul", name: "inula helenium" }, 
{ shortName: "ing", name: "ingluvin" }, 
{ shortName: "iod", name: "iodium" }, 
{ shortName: "iodof", name: "iodoformum" }, 
{ shortName: "ir-fl", name: "iris florentina" }, 
{ shortName: "ipom", name: "ipomia purpurea" }, 
{ shortName: "ir-foe", name: "iris foetidissima" }, 
{ shortName: "ir-g", name: "iris germanica" }, 
{ shortName: "iridium", name: "iridium" }, 
{ shortName: "jab", name: "jaborandi" }, 
{ shortName: "jac-c", name: "jacaranda caroba" }, 
{ shortName: "jac", name: "jacaranda gualandai" }, 
{ shortName: "jug-c", name: "juglans cinerea" }, 
{ shortName: "jatr", name: "jatropha curcas" }, 
{ shortName: "jug-r", name: "juglans regia" }, 
{ shortName: "juni", name: "juniperus virginiana" }, 
{ shortName: "junc", name: "juncus effusus" }, 
{ shortName: "kali-a", name: "kalium aceticum" }, 
{ shortName: "kali-br", name: "kalium bromatum" }, 
{ shortName: "kali-chl", name: "kalium chloricum" }, 
{ shortName: "kali-cy", name: "kalium cyanatum" }, 
{ shortName: "kali-fer", name: "kalium ferrocyanicum" }, 
{ shortName: "kali-n", name: "kalium nitricum" }, 
{ shortName: "kali-ox", name: "kalium oxalicum" }, 
{ shortName: "kali-ma", name: "kalium manganicum" }, 
{ shortName: "kalm", name: "kalmia latifolia o n" }, 
{ shortName: "kaol", name: "kaolin" }, 
{ shortName: "kiss", name: "kissingen" }, 
{ shortName: "kino", name: "kino" }, 
{ shortName: "lac-d", name: "lac defloratum" }, 
{ shortName: "lac-f", name: "lac felinum" }, 
{ shortName: "lact", name: "lactuca virosa" }, 
{ shortName: "lachn", name: "lachnanthes tinctoria" }, 
{ shortName: "lam", name: "lamium album" }, 
{ shortName: "lappa-a", name: "lappa arctium" }, 
{ shortName: "lact-ac", name: "lactic acid" }, 
{ shortName: "lat-m", name: "latrodectus mactans" }, 
{ shortName: "lath", name: "lathyrus sativus" }, 
{ shortName: "lappa-m", name: "lappa major" }, 
{ shortName: "lap-a", name: "lapis albus" }, 
{ shortName: "lec", name: "lecithin" }, 
{ shortName: "lepi", name: "lepidium bonariense" }, 
{ shortName: "lem-m", name: "lemna minor" }, 
{ shortName: "lept", name: "leptandra virginica" }, 
{ shortName: "lith", name: "lithium carbonicum" }, 
{ shortName: "linu-c", name: "linum cathar" }, 
{ shortName: "lith-m", name: "lithium muriaticum" }, 
{ shortName: "lob", name: "lobelia inflata" }, 
{ shortName: "lob-s", name: "lobelia syphilitica" }, 
{ shortName: "lup", name: "lupulus" }, 
{ shortName: "lob-c", name: "lobelia cardinalis" }, 
{ shortName: "lycps", name: "lycopus virginicus" }, 
{ shortName: "lycpr", name: "lycopersicum" }, 
{ shortName: "lyss", name: "lyssin (hydrophobinum)" }, 
{ shortName: "mag-arct", name: "magnetis polus arcticus" }, 
{ shortName: "mag-aust", name: "magnetis polus australis" }, 
{ shortName: "mag-p-a", name: "magnetis poli ambo" }, 
{ shortName: "mag-s", name: "magnesium sulphuricum" }, 
{ shortName: "maland", name: "malandrinum" }, 
{ shortName: "malar", name: "malaria officinalis" }, 
{ shortName: "manc", name: "mancinella (hippomanes)" }, 
{ shortName: "mang-m", name: "manganum muriaticum" }, 
{ shortName: "meli", name: "melilotus alba" }, 
{ shortName: "ment", name: "mentha piperita" }, 
{ shortName: "menis", name: "menispermum" }, 
{ shortName: "meph", name: "mephitis" }, 
{ shortName: "meny", name: "menyanthes" }, 
{ shortName: "merc-ac", name: "mercurius aceticus" }, 
{ shortName: "merc-i-f", name: "mercurius iodatus flavus" }, 
{ shortName: "merc-d", name: "mercurius dulcis" }, 
{ shortName: "merc-cy", name: "mercurius cyanatus" }, 
{ shortName: "merc-i-r", name: "mercurius iodatus ruber" }, 
{ shortName: "merc-n", name: "mercurius nitrosus" }, 
{ shortName: "merc-p-r", name: "mercurius praecipitatus ruber" }, 
{ shortName: "merl", name: "mercurialis" }, 
{ shortName: "merc", name: "mercurius vivus" }, 
{ shortName: "mit", name: "mitchella repens" }, 
{ shortName: "morph", name: "morphinum" }, 
{ shortName: "mygal", name: "mygale lasiodora e" }, 
{ shortName: "murx", name: "murex" }, 
{ shortName: "myos", name: "myosotis" }, 
{ shortName: "myric", name: "myrica cerifera" }, 
{ shortName: "myris", name: "myristica sebifera" }, 
{ shortName: "myrt", name: "myrtus communis" }, 
{ shortName: "naja", name: "naja tripudia" }, 
{ shortName: "naph", name: "naphthalin" }, 
{ shortName: "narcot", name: "narcotinum" }, 
{ shortName: "nat-ac", name: "natrium aceticum" }, 
{ shortName: "nat-a", name: "natrium arsenicatum" }, 
{ shortName: "vat-h", name: "natrium hypochlorosum" }, 
{ shortName: "nat-n", name: "natrium nitricum" }, 
{ shortName: "nicc", name: "niccolum" }, 
{ shortName: "nicc-s", name: "niccolum sulph" }, 
{ shortName: "nit-m-ac", name: "nitro muriatic acid" }, 
{ shortName: "nitro-o", name: "nitrogenium oxygenatum" }, 
{ shortName: "nit-s-d", name: "nitri spiritus dulcis" }, 
{ shortName: "nuph", name: "nuphar luteum" }, 
{ shortName: "nux-j", name: "nux juglans" }, 
{ shortName: "nym", name: "nymphaea odorata" }, 
{ shortName: "oena", name: "oenanthe crocata" }, 
{ shortName: "oci", name: "ocimum canum" }, 
{ shortName: "ol-an", name: "oleum animale" }, 
{ shortName: "ol-j", name: "oleum jecoris aselli" }, 
{ shortName: "onos", name: "onosmodium" }, 
{ shortName: "olnd", name: "oleander" }, 
{ shortName: "orig", name: "origanum majorana" }, 
{ shortName: "osm", name: "osmium" }, 
{ shortName: "ov", name: "ovinine" }, 
{ shortName: "ozone", name: "ozone (oxygenium)" }, 
{ shortName: "oxyt", name: "oxytropis lamberti" }, 
{ shortName: "paeon", name: "paeonia officinalis" }, 
{ shortName: "par", name: "paris ouadrifolia" }, 
{ shortName: "pall", name: "palladium" }, 
{ shortName: "pareir", name: "pareira brava" }, 
{ shortName: "paull", name: "paullinia pinnata" }, 
{ shortName: "ped", name: "pediculus capitis" }, 
{ shortName: "pen", name: "penthorum" }, 
{ shortName: "peti", name: "petiveria" }, 
{ shortName: "per", name: "persica" }, 
{ shortName: "petros", name: "petroselinum" }, 
{ shortName: "phal", name: "phallus impudicus" }, 
{ shortName: "phase", name: "phaseolus nanus" }, 
{ shortName: "phel", name: "phellandrium" }, 
{ shortName: "pic-ac", name: "picricum acidum" }, 
{ shortName: "phys", name: "physostigma" }, 
{ shortName: "phyt", name: "phytolacca decandra" }, 
{ shortName: "pimp", name: "pimpinella saxifraga" }, 
{ shortName: "pin-s", name: "pinus sylvestris" }, 
{ shortName: "plan", name: "plantago major" }, 
{ shortName: "pip-n", name: "piper nigrum" }, 
{ shortName: "pip-m", name: "piper methysticum" }, 
{ shortName: "plat-m", name: "platinum muriaticum" }, 
{ shortName: "plat", name: "platinum metallicum" }, 
{ shortName: "plumbg", name: "plumbago littoralis" }, 
{ shortName: "plect", name: "plectranthus" }, 
{ shortName: "podo", name: "podophyllum peltatum" }, 
{ shortName: "prun-p", name: "prunus padus" }, 
{ shortName: "poth", name: "pothos foetidus" }, 
{ shortName: "prun-s", name: "prunus spinosa" }, 
{ shortName: "polyg-h", name: "polygonum hydropiperoides" }, 
{ shortName: "pop-t", name: "populus tremuloides" }, 
{ shortName: "ptel", name: "ptelea trifoliata" }, 
{ shortName: "pulx", name: "pulex irritans" }, 
{ shortName: "puls-n", name: "pulsatilla nuttaliana" }, 
{ shortName: "puls", name: "pulsatilla nigricans" }, 
{ shortName: "rad", name: "radium" }, 
{ shortName: "pyrus", name: "pyrus americana" }, 
{ shortName: "ran-a", name: "ranunculus acris" }, 
{ shortName: "ran-s", name: "ranunculus sceleratus" }, 
{ shortName: "rheum", name: "rheum" }, 
{ shortName: "raph", name: "raphanus" }, 
{ shortName: "rat", name: "ratanhia" }, 
{ shortName: "rhus-a", name: "rhus aromatica" }, 
{ shortName: "rhus-r", name: "rhus radicans" }, 
{ shortName: "rhus-g", name: "rhus glabra" }, 
{ shortName: "rhus-v", name: "rhus venenata" }, 
{ shortName: "rob", name: "robinia pseudacacia" }, 
{ shortName: "sac-l", name: "saccharum lactis" }, 
{ shortName: "sacc", name: "saccharum album" }, 
{ shortName: "sal-ac", name: "salicylicum acidum" }, 
{ shortName: "sal-n", name: "salix niger" }, 
{ shortName: "salam", name: "salamander" }, 
{ shortName: "sang-n", name: "sanguinaria nitrica" }, 
{ shortName: "samb", name: "sambucus nigra" }, 
{ shortName: "sang", name: "sanguinaria canadensis" }, 
{ shortName: "sanic", name: "sanicula aqua" }, 
{ shortName: "sarr", name: "sarracenia purpurea" }, 
{ shortName: "scut", name: "scutellaria lateriflora" }, 
{ shortName: "sant", name: "santoninum" }, 
{ shortName: "senn", name: "senna" }, 
{ shortName: "serp", name: "serpentaria" }, 
{ shortName: "sin-a", name: "sinapis alba" }, 
{ shortName: "sin-n", name: "sinapis nigra" }, 
{ shortName: "sol-t-ae", name: "solanum tuberosum aegrotans" }, 
{ shortName: "sol-m", name: "solanum mammosum" }, 
{ shortName: "sol-o", name: "solanum oleraceum" }, 
{ shortName: "spig-m", name: "spigelia marilandica" }, 
{ shortName: "sol-v", name: "solidago virg aur" }, 
{ shortName: "sol-n", name: "solanum nigrum" }, 
{ shortName: "spig", name: "spigelia anthelmia" }, 
{ shortName: "spira", name: "spiranthes" }, 
{ shortName: "spong", name: "spongia tosta" }, 
{ shortName: "stach", name: "stachys betonica" }, 
{ shortName: "squil", name: "squilla hispanica" }, 
{ shortName: "stel", name: "stellaria media" }, 
{ shortName: "stict", name: "sticta pulmonaria" }, 
{ shortName: "still", name: "stillingia sylvatica" }, 
{ shortName: "stront", name: "strontium" }, 
{ shortName: "stroph", name: "strophanthus hispidus" }, 
{ shortName: "stry", name: "strychninum" }, 
{ shortName: "sumb", name: "sumbul" }, 
{ shortName: "symph", name: "symphytum officinale" }, 
{ shortName: "sym-r", name: "symphoricarpus racemosus" }, 
{ shortName: "tab", name: "tabacum" }, 
{ shortName: "tanac", name: "tanacetum vulgare" }, 
{ shortName: "tann", name: "tanninum" }, 
{ shortName: "tarax", name: "taraxacum" }, 
{ shortName: "tarent-c", name: "tarentula cubensis" }, 
{ shortName: "tart-ac", name: "tartaricum acid" }, 
{ shortName: "tax", name: "taxus baccata" }, 
{ shortName: "tep", name: "teplitz" }, 
{ shortName: "teucr", name: "teucrium marum verum" }, 
{ shortName: "thal", name: "thallium" }, 
{ shortName: "ter", name: "terebinthina" }, 
{ shortName: "thea", name: "thea sinensis" }, 
{ shortName: "thlaspi", name: "thlaspi bursa pastoris" }, 
{ shortName: "til", name: "tilia europoea" }, 
{ shortName: "trif-p", name: "trifolium pratense" }, 
{ shortName: "tong", name: "tongo" }, 
{ shortName: "tril", name: "trillium pendulum" }, 
{ shortName: "trio", name: "triosteum perfoliatum" }, 
{ shortName: "trom", name: "trombidium muscae domesticae" }, 
{ shortName: "tub", name: "tuberculinum" }, 
{ shortName: "tus-p", name: "tussilago petasites" }, 
{ shortName: "tus-f", name: "tussilago fragrans" }, 
{ shortName: "uran", name: "uranium nitricum" }, 
{ shortName: "upa", name: "upas tiente" }, 
{ shortName: "ust", name: "ustilago maydis" }, 
{ shortName: "uva", name: "uva ursi" }, 
{ shortName: "vac", name: "vaccininum" }, 
{ shortName: "valer", name: "valeriana" }, 
{ shortName: "vario", name: "variolinum" }, 
{ shortName: "verat-v", name: "veratrum viride" }, 
{ shortName: "urt-u", name: "urtica urens" }, 
{ shortName: "vinc", name: "vinca minor" }, 
{ shortName: "vib", name: "viburnum opulus" }, 
{ shortName: "verb", name: "verbascum thapsus" }, 
{ shortName: "vesp", name: "vespa crabro" }, 
{ shortName: "viol-t", name: "viola tricolor" }, 
{ shortName: "vip", name: "vipera" }, 
{ shortName: "viol-o", name: "viola odorata" }, 
{ shortName: "visc", name: "viscum album" }, 
{ shortName: "wild", name: "wildbad" }, 
{ shortName: "wye", name: "wyethia helenioides" }, 
{ shortName: "xan", name: "xanthoxylum fraxineum" }, 
{ shortName: "wies", name: "wiesbaden" }, 
{ shortName: "zinc-c", name: "zincum cyanatum" }, 
{ shortName: "zinc-ac", name: "zincum aceticum" }, 
{ shortName: "zinc-m", name: "zincum muriaticum" }, 
{ shortName: "zinc-ox", name: "zincum oxydatum" }, 
{ shortName: "yuc", name: "yucca" }, 
{ shortName: "zinc-s", name: "zincum sulphuricum" }, 
{ shortName: "zing", name: "zingiber" }, 
{ shortName: "ziz", name: "zizia aurea" },
]

db.getCollection('remedies').aggregate([
    {
        $lookup: {
            from: 'descriptions',
            localField: '_id',
            foreignField: 'remedy',
            as: 'descriptions',
        }
    },
    {
        $lookup: {
            from: 'symptoms',
            localField: '_id',
            foreignField: 'remedy',
            as: 'symptoms',
        }
    },
    {
        $match: {
//             $or: [
//                 { 'descriptions.0': { $exists: false } },
//                 { 'symptoms.0': { $exists: true } },
//             ]
                'descriptions.0': { $exists: false },
                'symptoms.0': { $exists: true }
        }
    },
    {
        $sort: { name: 1 }
    }
])

