export const REMEDY_PROPERTY = {
    LEFT: 1,
    RIGHT: 2,
    COLD: 3,
    WARM: 4,
    DIAGONALLY: 5,
    LEFT_UP_RIGHT_DOWN: 6,
    LEFT_DOWN_RIGHT_UP: 7,
    UMYSL: 8,
    ZAWROTY_GLOWY: 9,
    GLOWA: 10,
    OKO: 11,
    WZROK: 12,
    UCHO: 13,
    SLUCH: 14,
    NOS: 15,
    TWARZ: 16,
    JAMA_USTNA: 17,
    ZEBY: 18,
    GARDLO: 19,
    SZYJA: 20,
    ZOLADEK: 21,
    BRZUCH: 22,
    ODBYTNICA: 23,
    STOLEC: 24,
    PECHERZ_MOCZOWY: 25,
    NERKI: 26,
    GRUCZOL_KROKOWY: 27,
    CEWKA_MOCZOWA: 28,
    MOCZ: 29,
    MESKIE_NARZADY_PLCIOWE: 30,
    KOBIECE_NARZADY_PLCIOWE: 31,
    KRTAN_I_TCHAWICA: 32,
    ODDYCHANIE: 33,
    KASZEL: 34,
    PLWOCINA_ODKRZTUSZANIE: 35,
    KLATKA_PIERSIOWA: 36,
    PLECY: 37,
    KONCZYNY: 38,
    SEN: 39,
    DRESZCZE: 40,
    GORACZKA_GORACO: 41,
    POTY: 42,
    SKORA: 43,
    OBJAWY_OGOLNE: 44,
}

export const REMEDY_PROPERTY_NAME = {
    1: 'Lewa',
    2: 'Prawa',
    3: 'Pogorszenie pod wpływem zimna',
    4: 'Pogorszenie pod wpływem ciepła',
    5: 'Objawy występują po przekątnej',
    6: 'Lewa górna prawa dolna',
    7: 'Lewa dolna prawa górna',
    8: 'Umysł',
    9: 'Zawroty głowy',
    10: 'Głowa',
    11: 'Oko',
    12: 'Wzrok',
    13: 'Ucho',
    14: 'Słuch',
    15: 'Nos',
    16: 'Twarz',
    17: 'Jama ustna',
    18: 'Zęby',
    19: 'Garło',
    20: 'Szyja',
    21: 'Żołądek',
    22: 'Brzuch',
    23: 'Odbytnica',
    24: 'Stolec',
    25: 'Pęcherz moczowy',
    26: 'Nerki',
    27: 'Gruczoł krokowy',
    28: 'Cewka moczowa',
    29: 'Mocz',
    30: 'Męskie narządy płciowe',
    31: 'Kobiece narządy płciowe',
    32: 'Krtań i tchawica',
    33: 'Oddychanie',
    34: 'Kaszel',
    35: 'Plwocina (odkrztuszanie)',
    36: 'Klatka piersiowa',
    37: 'Plecy',
    38: 'Kończyny',
    39: 'Sen',
    40: 'Dreszcze',
    41: 'Gorączka, gorąco',
    42: 'Poty',
    43: 'Skóra',
    44: 'Objawy ogólne',

}

