import Remedy from '@models/remedy';
import { appendTextToFile, getFilesFromCatalog } from './helpers';
import DescriptionMamk from '@models/descriptionMamk';

const fs = require('fs');
const mammoth = require('mammoth');

export const createHTMLFromDocAndConvertToJSON = async (catalogPath = 'app/api/scripts/AIDocx') => {


            const arrOfFiles = await getFilesFromCatalog(catalogPath);
    
            for (const file of arrOfFiles) {

                // jesli danej nazwy nie ma w bazie to zapisz nowe remedium z tą właśnie nazwąi stworzonym JSONem 
                let remedyName = file.name.toLowerCase().replace('.docx', '');
                const mappedName = remediesNameList.find(item => item?.name === remedyName)
                if (mappedName) {
                    remedyName = mappedName?.dbName || mappedName?.name;
                }
                let remedy = await Remedy.findOne({ name: remedyName })

                if (!remedy?._id) {
                    // Create new remedy as it's not been i repertory e.g.! ['adonis vernalis','carcinosinum','lycopodium','pertussinum']
                    // USE mappedName.name
                    console.log('NOT FOUND: ', remedyName, mappedName)
                    await Remedy.create({ name: remedyName })
                    remedy = await Remedy.findOne({ name: remedyName })
                    // appendTextToFile('app/api/scripts/AIDocxTry', 'notInDbRemedies2', `${mappedName}: '', \n`)
                }

                try {
                    // Czytanie pliku DOCX
                    const buffer = fs.readFileSync(file.path);
             
                    // Konwersja do HTML
                    const result = await mammoth.convertToHtml({ buffer: buffer });
             
                    // Wynikowy HTML
                    const html = result.value;
                    await DescriptionMamk.create({ descriptionHtml: html, remedy: remedy?._id, remedyName: remedy.name })
                    
                    // Zapisz HTML do pliku lub zrób z nim coś innego
                    // appendTextToFile('app/api/scripts/AIDocxTry', remedyName, html)
                    console.log("Konwersja zakończona sukcesem! Zapisano do output.html", remedyName);
             
                } catch (error) {
                    console.error("Wystąpił błąd podczas konwersji: ", error);
                }





    
                // const response = await openai.chat.completions.create({
                //     model: "gpt-4o",
                //     messages: [
                //         {
                //         role: "user",
                //         content: [
                //             { 
                //                 type: "text",
                //                 text,
                //             },
                //             {
                //             type: "image_url",
                //             image_url: {
                //                 // "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
                //                 url: `data:image/jpg;base64,${base64Image}`
        
                //             },
                //             },
                //         ],
                //         },
                //     ],
                    
                // });
            }

};

export const remediesNameList = [
    { name: 'acidum fluoricum', dbName: 'fluoricum acidum' }, 
    { name: 'acidum nitricum', dbName: 'nitricum acidum' }, 
    { name: 'acidum phosforicum', dbName: 'phosphoricum acidum' }, 
    { name: 'acidum picricum', dbName: 'picricum acidum' }, 
    { name: 'adonis vernalis', dbName: '' }, 
    { name: 'agaricus', dbName: 'agaricus muscarius' }, 
    { name: 'apis', dbName: 'apis mellifica' }, 
    { name: 'arnika', dbName: 'arnica montana' }, 
    { name: 'barium carbonicum', dbName: 'baryta carbonica' }, 
    { name: 'barium iodatum', dbName: 'baryta iodata' }, 
    { name: 'barium muriaticum', dbName: 'baryta muriatica' }, 
    { name: 'barium sulfuricum', dbName: 'barium sulphuricum' }, 
    { name: 'bismuthum', dbName: 'bismuthum oxidum' }, 
    { name: 'borax veneta', dbName: 'borax' }, 
    { name: 'bovista lycoperdon', dbName: 'bovista' }, 
    { name: 'calcium carbonicum', dbName: 'calcarea carbonica' }, 
    { name: 'calcium fluoricum', dbName: 'calcarea fluorata' }, 
    { name: 'calcium fosforicum', dbName: 'calcarea phosphorica' }, 
    { name: 'calcium silicatum', dbName: 'calcarea silicata' }, 
    { name: 'calcium sulfuricum', dbName: 'calcarea sulphurica' }, 
    { name: 'camphora', dbName: 'camphora officinarum' }, 
    { name: 'cantharis vesicatoria', dbName: 'cantharis' }, 
    { name: 'capsicum annuum', dbName: 'capsicum' }, 
    { name: 'carcinosinum', dbName: '' }, 
    { name: 'chelidonium  majus', dbName: 'chelidonium majus' }, 
    { name: 'china', dbName: 'china officinalis' }, 
    { name: 'cimicifuga', dbName: 'cimicifuga racemosa' }, 
    { name: 'lachesis muta', dbName: 'lachesis' }, 
    { name: 'lycopodium clamatum', dbName: 'lycopodium clavatum' }, 
    { name: 'lycopodium', dbName: '' }, 
    { name: 'lyssinum', dbName: 'lyssin (hydrophobinum)' }, 
    { name: 'magnesium sulfuricum', dbName: 'magnesium sulphuricum' }, 
    { name: 'mercurius solubilis', dbName: 'mercurius vivus' }, 
    { name: 'mezerum', dbName: 'mezereum' }, 
    { name: 'naja', dbName: 'naja tripudia' }, 
    { name: 'passiflora incarnata', dbName: 'passiflora' }, 
    { name: 'pertussinum', dbName: '' }, 
    { name: 'platina', dbName: 'platinum metallicum' }, 
    { name: 'plumbum metalicum', dbName: 'plumbum metallicum' }, 
    { name: 'pulsatilla pratensis', dbName: 'pulsatilla nigricans', otherName: 'pulsatilla pratensis' }, 
    { name: 'radium bromatum', dbName: 'radium', otherName: 'radium bromatum' }, 
    { name: 'raphanus sativus', dbName: 'raphanus', otherName: 'raphanus sativus' }, 
    { name: 'sabadilla officinalis', dbName: 'sabadilla', otherName: 'sabadilla officinalis' }, 
    { name: 'sanicula', dbName: 'sanicula aqua' }, 
    { name: 'sarsaparilla officinalis', dbName: 'sarsaparilla', otherName: 'sarsaparilla officinalis' }, 
    { name: 'scutellaria laterifolia', dbName: 'scutellaria lateriflora' }, 
    { name: 'sulfur', dbName: 'sulphur' }, 
    { name: 'tuberkulina', dbName: 'tuberculinum' },
];


const names = [
"abies canadensis",
"abies nigra",
"abrotanum",
"absinthium",
"acalypha indica",
"acetic acid",
"aconitum cammarum",
"aconitum ferox",
"aconitum lycotonum",
"aconitum napellus",
"actaea spicata",
"aesculus glabra",
"aesculus hippocastanum",
"aethusa cynapium",
"agaricus emeticus",
"agaricus muscarius",
"agaricus phalloides",
"agnus castus",
"ailanthus",
"alcohol",
"aletris farinosa",
"allium cepa",
"allium sativum",
"aloe socotrina",
"alstonia constricta",
"alumen",
"alumina",
"alumina phosphorica",
"alumina silicata",
"aluminium metallicum",
"ambra grisea",
"ambrosia artemisiae folia",
"ammoniacum gummi",
"ammonium benzoicum",
"ammonium bromatum",
"ammonium carbonicum",
"ammonium causticum",
"ammonium muriaticum",
"amphisboena",
"amygdalae amarae aqua",
"amyl nitrite",
"anacardium occidentale",
"anacardium orientale",
"anagallis aryensis",
"anantherum muricatum",
"angustura vera",
"anilinum",
"anisum stellatum",
"anthemis nobilis",
"anthracinum",
"anthrokokali",
"antimonium arsenicosum",
"antimonium chloridum",
"antimonium crudum",
"antimonium oxydatum",
"antimonium sulph auratum",
"antimonium tartaricum",
"aphis chenopodii glauci",
"apis mellifica",
"apium graveolens",
"apocynum androsaemifolium",
"apocynum cannabinum",
"apomorphium",
"aralia racemosa",
"aranea diadema",
"aranea scinencia",
"argentum cyanidum",
"argentum metallicum",
"argentum muriaticum",
"argentum nitricum",
"arnica montana",
"arsenicum album",
"arsenicum hydrogenisatum",
"arsenicum iodatum",
"arsenicum metallicum",
"arsenicum nitricum",
"arsenicum sulphuratum flavum",
"arsenicum sulphuratum rubrum",
"artemisia vulgaris",
"arum dracontium",
"arum italicum",
"arum maculatum",
"arum triphyllum",
"arundo donax",
"arundo mauritanica",
"asa foetida",
"asarum europaeum",
"asclepias cornuti (syriaca)",
"asclepias tuberosa",
"asimina triloba",
"asparagus officinalis",
"astacus fluviatilis",
"asterias rubens",
"atropia sulphurica",
"atropinium",
"aurum arsenicum",
"aurum iodatum",
"aurum metallicum",
"aurum muriaticum",
"aurum muriaticum natronatum",
"aurum sulphuratum",
"badiaga",
"balsamum peruvianum",
"baptisia tinctoria",
"barium sulphuricum",
"bartfelder (acid spring)",
"baryta acetica",
"baryta carbonica",
"baryta iodata",
"baryta muriatica",
"belladonna",
"bellis perennis",
"benzinum",
"benzinum nitricum",
"benzoic acid",
"berberis vulgaris",
"bismuthum oxidum",
"blatta americana",
"blatta orientalis",
"boletus laricis",
"boracicum acidum",
"borax",
"bothrops lanceolatus",
"bovista",
"brachyglottis repens",
"bromium",
"brucea antidysenterica",
"bryonia alba",
"bufo rana",
"bufo sahytiensis",
"cactus grandiflorus",
"cadmium sulphuratum",
"cahinca",
"cainca",
"cajuputum",
"caladium seguinum",
"calcarea acetica",
"calcarea arsenica",
"calcarea carbonica",
"calcarea caustica",
"calcarea fluorata",
"calcarea iodata",
"calcarea phosphorica",
"calcarea silicata",
"calcarea sulphurica",
"calendula officinalis",
"calliandra houstoni",
"calotropis gigantea",
"caltha palustris",
"camphora officinarum",
"canchalagua",
"candida albicans",
"cannabis indica",
"cannabis sativa",
"cantharis",
"capsicum",
"carbo animalis",
"carbo vegetabilis",
"carbolic acid",
"carboneum hydrogenisatum",
"carboneum oxygenisatum",
"carboneum sulphuratum",
"carduus benedictus",
"carduus marianus",
"carlsbad",
"cascarilla",
"castanea vesca",
"castor equi",
"castoreum",
"caulophyllum thalictroides",
"causticum",
"ceanothus americanus",
"cedron",
"cenchris contortrix",
"centaurea tagana",
"cereus bonplandii",
"cereus serpentaria",
"cetrararia islandica",
"chamomilla",
"chelidonium majus",
"chenopodium anthelminticum",
"chenopodium glauci aphis",
"chenopodium vulvaria",
"chimaphila maculata",
"chimaphila umbellata",
"china officinalis",
"chininum arsenicosum",
"chininum brom",
"chininum sulphuricum",
"chionanthus virginica",
"chloralum",
"chloroformium",
"chlorum",
"cholesterinum",
"chromicum acidum",
"chromicum oxydatum",
"cicuta virosa",
"cimex",
"cimicifuga racemosa",
"cina",
"cinchona boliviana",
"cinchonium sulphuricum",
"cinnabaris",
"cinnamomum",
"cistus canadensis",
"citricum acidum",
"citrus limonum",
"citrus vulgaris",
"clematis erecta",
"cobaltum",
"coca",
"cocainum muriaticum",
"coccinella septempunctata",
"cocculus indicus",
"coccus cacti",
"cochlearia armoracia",
"codeinum",
"coffea cruda",
"coffea tosta",
"colchicum autumnale",
"collinsonia canadensis",
"colocynthis",
"colostrum",
"comocladia dentata",
"conium maculatum",
"convallaria majalis",
"convolvulus duartinus",
"copaiva officinalis",
"corallium rubrum",
"coriaria ruscifolia",
"cornus circinata",
"cornus florida",
"cornus seriea",
"cotyledon umbilicus",
"crocus sativus",
"crotalus cascavella",
"crotalus horridus",
"croton tiglium",
"cubeba officinalis",
"culex moscae",
"cundurango",
"cuprum aceticum",
"cuprum arsenicosum",
"cuprum metallicum",
"cuprum nitricum",
"cuprum sulphuricum",
"curare",
"cyclamen europaeum",
"cypripedium pubescens",
"daphne indica",
"derris pinnata",
"digitalis purpurea",
"dioscorea villosa",
"dirca palustris",
"dolichos pruriens",
"doryphora",
"drosera rotundifolia",
"duboisinum",
"dulcamara",
"echinacea angustifolia",
"elaps corallinus",
"elaterium",
"epigea repens",
"equisetum hyemale",
"erechthites hieracifolia",
"erigeron canadense",
"eryngium aquaticum",
"ether",
"eucalyptus globulus",
"eugenia jambos",
"euonymus europaeus",
"eupatorium perfoliatum",
"eupatorium purpureum",
"euphorbium",
"euphrasia officinalis",
"fagopyrum",
"ferrum aceticum",
"ferrum arsenicosum",
"ferrum iodatum",
"ferrum magneticum",
"ferrum metallicum",
"ferrum muriaticum",
"ferrum phosphoricum",
"ferrum picricum",
"ferrum sulphuricum",
"filix mas",
"fluoricum acidum",
"formica rufa",
"fragaria vesca",
"fupion",
"gadus morrhua",
"gallicum acidum",
"gambogia",
"gelsemium sempervirens",
"genista tinctoria",
"gentiana cruciata",
"gentiana lutea",
"geranium maculatum",
"gettisburg water",
"ginseng",
"glanderine",
"glonoinum",
"gnaphalium",
"gossypium herbaceum",
"granatum punica",
"graphites",
"gratiola officinalis",
"grindelia robusta",
"guaco",
"guaiacum",
"guano australis",
"guarana",
"guarea",
"gymnocladus",
"haematoxylon",
"hamamelis virginica",
"hecla lava",
"hedeoma pulegioides",
"helleborus niger",
"heloderma",
"helonias dioica",
"hepar sulphuris calcareum",
"hippomanes",
"hippozanium",
"homarus",
"hura braziliensis",
"hydrangea arborescens",
"hydrastis canadensis",
"hydrocotyle asiatica",
"hydrocyanicum acidum",
"hyoscyamus niger",
"hypericum perforatum",
"iberis amara",
"ictodes foetida",
"ignatia amara",
"illicium anisatum",
"indigo",
"indium metallicum",
"ingluvin",
"inula helenium",
"iodium",
"iodoformum",
"ipecacuanha",
"ipomia purpurea",
"iridium",
"iris florentina",
"iris foetidissima",
"iris germanica",
"iris versicolor",
"jaborandi",
"jacaranda caroba",
"jacaranda gualandai",
"jalapa",
"jatropha curcas",
"juglans cinerea",
"juglans regia",
"juncus effusus",
"juniperus virginiana",
"kalium aceticum",
"kalium arsenicosum",
"kalium bichromicum",
"kalium bromatum",
"kalium carbonicum",
"kalium chloricum",
"kalium cyanatum",
"kalium ferrocyanicum",
"kalium iodatum",
"kalium manganicum",
"kalium muriaticum",
"kalium nitricum",
"kalium oxalicum",
"kalium phosphoricum",
"kalium silicatum",
"kalium sulphuricum",
"kalmia latifolia",
"kaolin",
"kino",
"kissingen",
"kreosotum",
"lac caninum",
"lac defloratum",
"lac felinum",
"lachesis",
"lachnanthes tinctoria",
"lactic acid",
"lactuca virosa",
"lamium album",
"lapis albus",
"lappa arctium",
"lappa major",
"lathyrus sativus",
"latrodectus mactans",
"laurocerasus",
"lecithin",
"ledum palustre",
"lemna minor",
"lepidium bonariense",
"leptandra virginica",
"lilium tigrinum",
"linum cathar",
"lithium carbonicum",
"lithium muriaticum",
"lobelia cardinalis",
"lobelia inflata",
"lobelia syphilitica",
"lupulus",
"lycopersicum",
"lycopodium clavatum",
"lycopus virginicus",
"lyssin (hydrophobinum)",
"magnesium carbonicum",
"magnesium muriaticum",
"magnesium phosphoricum",
"magnesium sulphuricum",
"magnetis poli ambo",
"magnetis polus arcticus",
"magnetis polus australis",
"malandrinum",
"malaria officinalis",
"mancinella (hippomanes)",
"manganum",
"manganum muriaticum",
"medorrhinum",
"melilotus alba",
"menispermum",
"mentha piperita",
"menyanthes",
"mephitis",
"mercurialis",
"mercurius aceticus",
"mercurius corrosivus",
"mercurius cyanatus",
"mercurius dulcis",
"mercurius iodatus flavus",
"mercurius iodatus ruber",
"mercurius nitrosus",
"mercurius praecipitatus ruber",
"mercurius sulphuricus",
"mercurius vivus",
"mezereum",
"millefolium",
"mitchella repens",
"morphinum",
"moschus",
"murex",
"muriaticum acidum",
"mygale lasiodora e",
"myosotis",
"myrica cerifera",
"myristica sebifera",
"myrtus communis",
"naja tripudia",
"naphthalin",
"narcotinum",
"natrium aceticum",
"natrium arsenicatum",
"natrium carbonicum",
"natrium hypochlorosum",
"natrium muriaticum",
"natrium nitricum",
"natrium phosphoricum",
"natrium silicatum",
"natrium sulphuricum",
"niccolum",
"niccolum sulph",
"nitri spiritus dulcis",
"nitricum acidum",
"nitro muriatic acid",
"nitrogenium oxygenatum",
"nuphar luteum",
"nux juglans",
"nux moschata",
"nux vomica",
"nymphaea odorata",
"ocimum canum",
"oenanthe crocata",
"oleander",
"oleum animale",
"oleum jecoris aselli",
"onosmodium",
"opium",
"origanum majorana",
"oscillococcinum",
"osmium",
"ovinine",
"oxalicum acidum",
"oxytropis lamberti",
"ozone (oxygenium)",
"paeonia officinalis",
"palladium",
"pareira brava",
"paris ouadrifolia",
"passiflora",
"paullinia pinnata",
"pediculus capitis",
"penthorum",
"persica",
"petiveria",
"petroleum",
"petroselinum",
"phallus impudicus",
"phaseolus nanus",
"phellandrium",
"phosphoricum acidum",
"phosphorus",
"physostigma",
"phytolacca decandra",
"picricum acidum",
"pilocarpinum",
"pimpinella saxifraga",
"pinus sylvestris",
"piper methysticum",
"piper nigrum",
"plantago major",
"platinum metallicum",
"platinum muriaticum",
"plectranthus",
"plumbago littoralis",
"plumbum metallicum",
"podophyllum peltatum",
"polygonum hydropiperoides",
"populus tremuloides",
"pothos foetidus",
"prunus padus",
"prunus spinosa",
"psorinum",
"ptelea trifoliata",
"pulex irritans",
"pulsatilla nigricans",
"pulsatilla nuttaliana",
"pyrogenium",
"pyrus americana",
"radium",
"ranunculus acris",
"ranunculus bulbosus",
"ranunculus sceleratus",
"raphanus",
"ratanhia",
"rheum",
"rhododendron",
"rhus aromatica",
"rhus glabra",
"rhus radicans",
"rhus toxicodendron",
"rhus venenata",
"robinia pseudacacia",
"rumex crispus",
"ruta graveolens",
"sabadilla",
"sabal serrulata",
"sabina",
"saccharum album",
"saccharum lactis",
"salamander",
"salicylicum acidum",
"salix niger",
"sambucus nigra",
"sanguinaria canadensis",
"sanguinaria nitrica",
"sanicula aqua",
"santoninum",
"sarracenia purpurea",
"sarsaparilla",
"scutellaria lateriflora",
"secale cornutum",
"selenium",
"senecio aureus",
"senega",
"senna",
"sepia",
"serpentaria",
"silicea",
"sinapis alba",
"sinapis nigra",
"solanum mammosum",
"solanum nigrum",
"solanum oleraceum",
"solanum tuberosum aegrotans",
"solidago virg aur",
"spigelia anthelmia",
"spigelia marilandica",
"spiranthes",
"spongia tosta",
"squilla hispanica",
"stachys betonica",
"stannum metallicum",
"staphysagria",
"stellaria media",
"sticta pulmonaria",
"stillingia sylvatica",
"stramonium",
"strontium",
"strophanthus hispidus",
"strychninum",
"sulphur",
"sulphur iodatum",
"sulphuricum acidum",
"sumbul",
"symphoricarpus racemosus",
"symphytum officinale",
"syphilinum",
"tabacum",
"tanacetum vulgare",
"tanninum",
"taraxacum",
"tarentula cubensis",
"tarentula hispanica",
"tartaricum acid",
"taxus baccata",
"tellurium",
"teplitz",
"terebinthina",
"teucrium marum verum",
"thallium",
"thea sinensis",
"theridion",
"thlaspi bursa pastoris",
"thuja occidentalis",
"tilia europoea",
"tongo",
"trifolium pratense",
"trillium pendulum",
"triosteum perfoliatum",
"trombidium muscae domesticae",
"tuberculinum",
"tussilago fragrans",
"tussilago petasites",
"upas tiente",
"uranium nitricum",
"urtica urens",
"ustilago maydis",
"uva ursi",
"vaccininum",
"valeriana",
"variolinum",
"veratrum album",
"veratrum viride",
"verbascum thapsus",
"vespa crabro",
"vespa vulgaris",
"viburnum opulus",
"vinca minor",
"viola odorata",
"viola tricolor",
"vipera",
"viscum album",
"wiesbaden",
"wildbad",
"wyethia helenioides",
"xanthoxylum fraxineum",
"yucca",
"zincum aceticum",
"zincum cyanatum",
"zincum metallicum",
"zincum muriaticum",
"zincum oxydatum",
"zincum phosphoricum",
"zincum sulphuricum",
"zingiber",
"zizia aurea",
]